# Generated by Django 4.1.7 on 2023-03-17 07:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(upload_to=account.models.user_upload_path),
        ),
    ]
