# Generated by Django 4.1.7 on 2023-03-13 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_post_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='users_comments', to='account.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='users_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
