# Generated by Django 4.1.7 on 2023-03-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_post_comments_post_likes_post_share_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='share',
            new_name='shares',
        ),
    ]
