# Generated by Django 4.1.7 on 2023-03-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_share_post_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videos',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(null=True, to='account.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.ManyToManyField(null=True, to='account.video'),
        ),
    ]
