# Generated by Django 4.1.7 on 2023-03-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_post_profile_alter_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='videos',
            new_name='video',
        ),
    ]
