# Generated by Django 4.1.7 on 2023-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='account.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='account.image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.ManyToManyField(to='account.video'),
        ),
    ]
