# Generated by Django 4.1.7 on 2023-03-21 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_post_saved_by_delete_postsaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
